name: Notion Daily Snapshot

on:
  schedule:
    # Esto ejecuta el script todos los días a las 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Permite ejecutarlo manualmente para probar

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Instalar librerías
        run: pip install requests pandas

      - name: Ejecutar Script
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          CARTERA_DB_ID: ${{ secrets.CARTERA_DB_ID }}
          HISTORIAL_DB_ID: ${{ secrets.HISTORIAL_DB_ID }}
        run: python Date_Tracker.py
